.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x20000 .\gfx\jp\font.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x7E728 .\gfx\jp\score_topmenu_data.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x211D0 .\gfx\jp\score_mainmenu_data.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x1930 .\gfx\jp\score_topmenu_bar.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x8CA60 .\gfx\jp\score_ui.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x1DC8 .\gfx\jp\score_ui_track.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x36B88 .\gfx\jp\score_topmenu_score.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0xBAC10 .\gfx\jp\score_new_prompt.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0x3648 .\gfx\jp\score_new_window.chr
.\tools\decompress.py .\roms\OngakuTsukuruJP.sfc 0xB8240 .\gfx\jp\message_window.chr
