.\tools\compress.py .\gfx\en\font.chr .\gfx\en\tmp\font.chr.cmp
.\tools\compress.py .\gfx\en\score_topmenu_bar.chr .\gfx\en\tmp\score_topmenu_bar.chr.cmp
.\tools\compress.py .\gfx\en\score_topmenu_score.chr .\gfx\en\tmp\score_topmenu_score.chr.cmp
.\tools\compress.py .\gfx\en\score_topmenu_data.chr .\gfx\en\tmp\score_topmenu_data.chr.cmp
.\tools\compress.py .\gfx\en\score_new_prompt.chr .\gfx\en\tmp\score_new_prompt.chr.cmp
.\tools\compress.py .\gfx\en\score_new_window.chr .\gfx\en\tmp\score_new_window.chr.cmp
.\tools\compress.py .\gfx\en\score_ui.chr .\gfx\en\tmp\score_ui.chr.cmp
.\tools\compress.py .\gfx\en\score_ui_track.chr .\gfx\en\tmp\score_ui_track.chr.cmp
.\tools\compress.py .\gfx\en\message_window.chr .\gfx\en\tmp\message_window.chr.cmp
